alias d="du -ach"
alias dt='cd /mnt/c/Users/dude1/Desktop'
alias dl='cd /mnt/c/Users/dude1/Downloads'
alias fuck="thefuck"
alias aws1='sudo ssh -i ~/.ssh/AWSKeyPair1.pem ec2-user@ec2-54-213-224-205.us-west-2.compute.amazonaws.com'
alias j="jobs"
alias matrix='cmatrix'
alias fire='cacafire'
alias notes='cd ~/mynotes;ls'
alias ms='cd ~/myscripts;ls'
alias vim='nvim'
alias open='cmd.exe \C start'
# alias py="python3"
# alias python="python3"
alias ..='cd ..'
alias apt-get='sudo apt-get'
alias h='history'
alias wcl='wc -l'
alias reload='source ~/.bashrc'
alias v="vim"
alias vimwiki='vim +VimwikiIndex'
