alias d="du -ach"
alias gs="git status"
alias dt='cd /mnt/c/Users/dude1/Desktop'
alias dl='cd /mnt/c/Users/dude1/Downloads'
alias fuck="thefuck"
alias j="jobs"
alias matrix='cmatrix'
alias fire='cacafire'
alias notes='cd ~/mynotes;ls'
alias ms='cd ~/myscripts;ls'
alias vim='nvim'
alias open='cmd.exe \C start'
# alias py="python3"
# alias python="python3"
alias ..='cd ..'
alias apt-get='sudo apt-get'
alias h='history'
alias wcl='wc -l'
alias reload='source ~/.bashrc'
alias v="vim"
alias vimwiki='vim +VimwikiIndex'
